name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application name to deploy'
        required: true
        type: string
      version:
        description: 'Version to deploy to production'
        required: true
        type: string

jobs:
  deploy-production:
    runs-on: [self-hosted, linux, x64]
    if: github.ref == 'refs/heads/main'
    environment: production
    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Update ArgoCD repo (production)
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/igor-siergiej/argonaut.git argonaut-repo
          cd argonaut-repo
          git config user.email "argonaut-bot@users.noreply.github.com"
          git config user.name "argonaut-bot"
          # Replace the final tag on every image line; skip digest refs (with '@')
          sed -i -E "s|^([[:space:]]*image:[[:space:]]*[^@]+):([^:@[:space:]]+)([[:space:]]*)$|\\1:${{ inputs.version }}\\3|" apps/${{ inputs.app_name }}/overlays/production/patch-deployment.yaml
          git add apps/${{ inputs.app_name }}/overlays/production/patch-deployment.yaml
          git commit -m "Update ${{ inputs.app_name }} production to version ${{ inputs.version }}"
          git push origin main